# Workflow to print OIDC token claims
name: print OIDC token claims

on:
  workflow_dispatch:

permissions:
  id-token: write

jobs:
  print-oidc-token:
    runs-on: ubuntu-latest
    environment: testing
    steps:
         
    # print oidc token claims
    - name: print oidc token claims
      run: |
          IDTOKEN=$(curl -s -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL" -H "Accept: application/json; api-version=2.0" -H "Content-Type: application/json"  | jq -r '.value')
          jwtd() {
            if [[ -x $(command -v jq) ]]; then
                jq -R 'split(".") | .[1] | @base64d | fromjson' <<< "${1}" > jwt_claims.json
                cat jwt_claims.json
            fi
          }
          jwtd $IDTOKEN
    - name: print github, job and runner context
      env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          JOB_CONTEXT: ${{ toJson(job) }}
          RUNNER_CONTEXT: ${{ toJson(runner) }}
      run: |
          echo "$GITHUB_CONTEXT"
          echo "$JOB_CONTEXT"
          echo "$RUNNER_CONTEXT"
