# Workflow generates ID Token and validates Subject claim Values
name: Generate and Validate ID Token

on:
  # Can be triggered manually from UI or through API call
  workflow_dispatch:
    inputs:
      subjectClaim:
        description: 'Subject Claim Value'
        required: false
        type: string

permissions:
  id-token: write

jobs:
  generate-validate:
    runs-on: ubuntu-latest
    steps:
    - name: Generate ID Token When OptOut
      id: generateClaim
      run: |
        IDTOKEN=$(curl -s -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=github" -H "Accept: application/json; api-version=2.0" -H "Content-Type: application/json"  | jq -r '.value')
        JWT=$(jq -R 'split(".") | .[1] | @base64d | fromjson | .sub' <<< "$IDTOKEN")
        echo "Token : $JWT"
        echo "::set-output name=REPO_CLAIM::$JWT"
    - name: Print Sub Claim
      run: |
        echo "Subject Claim of Repo - .${{ steps.generateClaim.outputs.REPO_CLAIM }}."
        echo "Subject claim as Input - .${{ github.event.inputs.subjectClaim }}."
        A1="Apple"
        A2="Apple"
        echo "Check - $((A1==A2))"
        echo "Both are equal - ${{ (steps.generateClaim.outputs.REPO_CLAIM==github.event.inputs.subjectClaim) }}"
    - name: Check for Sub Claim Match
      if: ${{ steps.generateClaim.outputs.REPO_CLAIM != github.event.inputs.subjectClaim }}
      run: echo "::error::Subject Claim mismatch found" && exit 1
