name: Test Token

on: [workflow_dispatch]

permissions:
  id-token: write
  contents: write

jobs:
  updateSubClaim:
    runs-on: ubuntu-latest
    steps:
     - name: Generate ID Token When OptOut
       run: |
          IDTOKEN=$(curl -s -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=github" -H "Accept: application/json; api-version=2.0" -H "Content-Type: application/json"  | jq -r '.value')
          jwtd() {
            if [[ -x $(command -v jq) ]]; then
                echo "Token : "
                jq -R 'split(".") | .[1] | @base64d | fromjson' <<< "${1}"
               echo "Signature: $(echo "${1}" | awk -F'.' '{print $3}')"
            fi
          }
          jwtd $IDTOKEN  
