# Workflow generates ID Token and validates Subject claim Values
name: Generate and Validate ID Token

on:
  # Can be triggered manually from UI or through API call
  workflow_dispatch:
    inputs:
      subjectClaim:
        description: 'Subject Claim Value'
        required: true
        type: string
      optStatus:
        description: 'Opt-in/Opt-out Value'
        required: false
        type: string
permissions:
  id-token: write

jobs:
  generate-validate:
    runs-on: ubuntu-latest
    steps:
    - name: Generate ID Token When OptOut
      id: generateClaim
      run: |
        IDTOKEN=$(curl -s -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=github" -H "Accept: application/json; api-version=2.0" -H "Content-Type: application/json"  | jq -r '.value')
        JWT=$(jq -R 'split(".") | .[1] | @base64d | fromjson' <<< "$IDTOKEN")
        SUB_CLAIM=$(jq -r '.sub' <<< "$JWT")
        echo "Repo Sub Claim : $SUB_CLAIM"
        echo "::set-output name=REPO_CLAIM::$SUB_CLAIM"
    - name: Check for Sub Claim Match
      if: ${{ steps.generateClaim.outputs.REPO_CLAIM != github.event.inputs.subjectClaim }}
      run: echo "::error::Subject Claim mismatch found" && exit 1
    - name: Print Success
      env:
        optValue: ${{ github.event.inputs.optStatus }}
      run: echo "Subject Claim Matches successfully for ${{ env.optValue }}"
